### ISSUE TITLE
HDF5 database file prone to corruption

### ISSUE THREAD

**Issue by ViktorKaz** [alan-turing-institute/mlaut#25]
H5 files seem to be unreliable and prone to corruption.

The following errors have been observed:

- h5 file becomes corrupt when trying to delete multiple groups via HDF View.
- h5 file becomes corrupt after making predictions.

**Comment by fkiraly** [comment]
Re-opening as corruption has been observed (discussion on Jan 22, 2019) to occur too when experiments interrupted during writing of results or models (not addressed).

**Comment by ViktorKaz** [comment]
This seems to be a limitation of the HDF5 format. The file is prone to corruption if not closed properly, e.g. if the orchestrator task is killed. New design allows to implement different backends for loading and saving data.
