### ISSUE TITLE
API discussion/refactoring

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/mlaut#28]
We should maybe plan to re-factor the API in the near future.

My main issue is that file paths are passed to split_datasets and orchestrator and analyze_results, hence assuming the specific parameters of a local file system. The abstraction is not extensible, and cannot cope easily with a internet or remote database location, say.
Instead, a reference to a data class which is a facade abstraction should be passed which would solve the issue.

More precisely:
- data class should provide a unified public interface to the data location and manage output/input technicalities *internally*
- split_datasets should be passed a reference to data class
- orchestrator should be provided with a reference to data class and use it as a facade
- analyse_results should be provided either with a reference to a data class or an output of the orchestrator class

An even cleaner design might involve *two* data objects - one for data location, and one for output/results location (might even separate outputs from intermediate results). These could be bundled together in a dataIO object that is passed around, rather than having the user pass multiple facade references.

**Comment by ViktorKaz** [comment]
Apologies, I only just saw that you opened some additional issues.

The current workflow is the following:

```python
# setup database
data = Data()
input_io = data.open_hdf5('data/delgado.hdf5', mode='a')
out_io = data.open_hdf5('data/classification.hdf5', mode='a')

# split datasets
dts_names_list, dts_names_list_full_path = data.list_datasets(hdf5_io=input_io, hdf5_group='delgado_datasets/')
split_dts_list = data.split_datasets(hdf5_in=input_io, hdf5_out=out_io, dataset_paths=dts_names_list_full_path, verbose=False)

# select estimators
est = ['RandomForestClassifier','BaggingClassifier','GradientBoostingClassifier','SVC','GaussianNaiveBayes','BernoulliNaiveBayes','NeuralNetworkDeepClassifier','PassiveAggressiveClassifier','BaselineClassifier']
estimators = instantiate_default_estimators(estimators=est)
# run experiments
orchest = Orchestrator(hdf5_input_io=input_io, hdf5_output_io=out_io, dts_names=dts_names_list,
                 original_datasets_group_h5_path='delgado_datasets/')
orchest.run(modelling_strategies=estimators, verbose=True)
```

Ignoring the other issues raised for the time being such as #35 #33 the workflow will be changed to:

```python
# I will bundle input io and output io in one object
data = Data()
data.set_input_io(<path to file>, mode=<read, write, append>)
data.set_output_io(<path to file>, mode=<read, write, append>)
data.split_datasets()

# this object will be passed to the orchestrator
orechestrator = Orchestrator(data)
orchestrator.run(estimators)
```

**Comment by ViktorKaz** [comment]
This is now implemented in branch `improved_workflow`.

Below is an example of the new workflow.

```python
from mlaut.data import Data
import pydataset
from mlaut.experiments import Orchestrator
from mlaut.estimators.baseline_estimators import Baseline_Classifier
from mlaut.estimators.bayes_estimators import Gaussian_Naive_Bayes
from mlaut.estimators.decision_trees import Decision_Tree_Classifier

from sklearn import preprocessing
acme = pydataset.data('acme')
aids = pydataset.data('aids')
iris = pydataset.data('iris')

acme_meta = {
    'class_name': 'acme',
    'source':'pydataset',
    'dataset_name':'acme'
}

aids_meta = {
    'class_name': 'adult',
    'source':'pydataset',
    'dataset_name':'aids'
}

iris_meta = {
    'class_name': 'Species',
    'source':'pydataset',
    'dataset_name':'iris'
}
#transform labels for iris
le = preprocessing.LabelEncoder()
le.fit(iris['Species'])
iris['Species']=le.transform(iris['Species'])


data = Data(hdf5_datasets_group='pydata')
data.set_io(input_data='data/test_input.h5', output_data='data/test_output.h5')

datasets = [acme, aids, iris]
metadata = [acme_meta, aids_meta, iris_meta]
data.pandas_to_db(datasets=datasets, dts_metadata=metadata)
data.split_datasets()

orcheststrator = Orchestrator(data)
orcheststrator.run(modelling_strategies=[Baseline_Classifier(), Decision_Tree_Classifier(), Gaussian_Naive_Bayes()])

```

**Comment by fkiraly** [comment]
Reopening following yesterday's discussion, with further comments below.
I think the re-factor is excellent, but not fully complete.

**Comment by fkiraly** [comment]
Comment 1: I think the "data facade" class should not do the re-sampling etc.
This should be with the orchestrator, as the re-sampling is part of an experiment.
Of course, one may want to pre-specify the splits, in which case these would be passed via a re-sampling object.

I would also recommend to specify explicit interface points to set the components of the benchmarking workflow, i.e., the re-sampling strategies, modelling strategies, and data.

This slight re-factor might look like this:

```python
orchestrator = Orchestrator()
orchestrator.set_data(data)
orchestrator.set_resampling(single_split())
orchestrator.set_strategies([Baseline_Classifier(), Decision_Tree_Classifier(), Gaussian_Naive_Bayes()])
orchestrator.run()
```

One may add fine-grained control for the running by, instead of the one run() line, optionally replacing it by the following

```python
orchestrator.prepare_resampling()
orchestrator.make_predictions()
orchestrator.compute_losses()
```

Similarly, instead of setting up the orchestrator with the setters, one may construct it, in a slightly more difficult-to-read way, with the different components directly:


```python
orchestrator = Orchestrator(data = data, resampling = single_split(), strategies = [Baseline_Classifier(), Decision_Tree_Classifier(), Gaussian_Naive_Bayes()])

orchestrator.run()
```

**Comment by fkiraly** [comment]
Comment 2:

data class should also be a facade for in-memory data frame collection - or a single dataframe/metadata pair, so sth like the following should also work

```python

data = Data()

datasets = [acme, aids, iris]
metadata = [acme_meta, aids_meta, iris_meta]
data.pandas_inmemory(datasets=datasets, dts_metadata=metadata)
data.set_io(resultsobj = resultsobj)

```

or similar.
One might consider having an abstract generic and inheriting the different kinds of data containers, but that might make it more difficult to use than a modular facade with a dynamic interface.

**Comment by ViktorKaz** [comment]
Implemented improved workflow. Merged with master branch.

Example of the workflow below:

```python
        aids = pydataset.data('aids')
	iris = pydataset.data('iris')

	aids_meta = {
	'target': 'adult',
	'source':'pydataset',
	'dataset_name':'aids'
	}

	iris_meta = {
	'target': 'Species',
	'source':'pydataset',
	'dataset_name':'iris'
	}

	le = preprocessing.LabelEncoder()
	le.fit(iris['Species'])
	iris['Species']=le.transform(iris['Species'])

	data = Data(hdf5_datasets_group='pydata')
	data.set_io(input_data='data/test_input.h5', output_data='data/test_output.h5')

	datasets = [aids, iris]
	metadata = [aids_meta, iris_meta]
	data.pandas_to_db(datasets=datasets, dts_metadata=metadata)

	#orchestration
	aids_data = DatasetHDF5(hdf5_path='data/test_input.h5',dataset_path='pydata/aids')
	iris_data = DatasetHDF5(hdf5_path='data/test_input.h5',dataset_path='pydata/iris')

	cv = Single_Split(cv=train_test_split)
	datasets = [aids_data,iris_data]
	strategies = [Baseline_Classifier(), Decision_Tree_Classifier(), Gaussian_Naive_Bayes()]


	result = ResultHDF5(hdf5_path='data/test_result.h5', 
                    predictions_save_path='predictions', 
                    trained_strategies_save_path='data/trained_estimators')

	orchestrator = Orchestrator(datasets=datasets, strategies=strategies, cv = cv, result=result)
	orchestrator.run()
```
