### ISSUE TITLE
refactoring analyze_results?

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/mlaut#30]
analyze_results is not as extensible as one could wish as the user needs to add a method or inherit from the class. Could the concept of "performance quantifiers" be made abstract and modular, similar to the "metric" design in mlr?

**Comment by ViktorKaz** [comment]
Is this the mlr functionality that you are referring to: https://mlr.mlr-org.com/articles/tutorial/create_measure.html

**Comment by ViktorKaz** [comment]
as discussed, a simpler version of the mlr functionality is already implemented in MLaut. The user can define different Score functions. A link to the code can be found [here](https://github.com/alan-turing-institute/mlaut/blob/master/mlaut/analyze_results/scores.py).
