### ISSUE TITLE
redundant arguments in dts_names_list_full_path

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/mlaut#33]
dts_names_list_full_path argument to split_datasets seems redundant – doesn’t the data class have the full information?

**Comment by ViktorKaz** [comment]
This is fixed with #28

**Comment by fkiraly** [comment]
Reopening following yesterday's discussion, with further comments below.
I think the re-factor is excellent, but not fully complete.

**Comment by fkiraly** [comment]
Comment 1: I think the "data facade" class should not do the re-sampling etc.
This should be with the orchestrator, as the re-sampling is part of an experiment.
Of course, one may want to pre-specify the splits, in which case these would be passed via a re-sampling object.

I would also recommend to specify explicit interface points to set the components of the benchmarking workflow, i.e., the re-sampling strategies, modelling strategies, and data.

This slight re-factor might look like this:

```python
orcheststrator = Orchestrator()
orchestrator.set_data(data)
orchestrator.set_resampling(single_split())
orchestrator.set_strategies([Baseline_Classifier(), Decision_Tree_Classifier(), Gaussian_Naive_Bayes()])
orcheststrator.run()
```

One may add fine-grained control for the running by, instead of the one run() line, doing the follows

```python
orcheststrator.prepare_resampling()
orchestrator.make_predictions()
orchestrator.compute_losses()
```

Similarly, instead of setting up the orchestrator with the setters, one may construct it, in a slightly more difficult-to-read way, with the different components directly:


```python
orcheststrator = Orchestrator(data = data, resampling = single_split(), strategies = [Baseline_Classifier(), Decision_Tree_Classifier(), Gaussian_Naive_Bayes()])

orcheststrator.run()
```

**Comment by fkiraly** [comment]
whoops, commented in, and re-opened the wrong issue.
Fixing this and moving everything ot the right one.
